# defined exercises for unambiguous naming conventions and having a select premade list
# sourced directly from https://www.strengthlog.com/exercise-directory/

[chest]
assisted-dip = "Assisted Dip"
band-assisted-bench-press = "Band Assisted Bench Press"
bar-dip = "Bar Dip"
bench-press = "Bench Press"
bench-press-against-band = "Bench Press Against Band"
board-press = "Board Press"
cable-chest-press = "Cable Chest Press"
close-grip-bench-press = "Close Grip Bench Press"
close-grip-feet-up-bench-press = "Close Grip Feet Up Bench Press"
decline-bench-press = "Decline Bench Press"
decline-push-up = "Decline Push Up"
dumbbell-chest-fly = "Dumbbell Chest Fly"
dumbbell-chest-press = "Dumbbell Chest Press"
dumbbell-decline-chest-press = "Dumbbell Decline Chest Press"
dumbbell-floor-press = "Dumbbell Floor Press"
dumbbell-pullover = "Dumbbell Pullover"
feet-up-bench-press = "Feet Up Bench Press"
floor-press = "Floor Press"
incline-bench-press = "Incline Bench Press"
incline-dumbbell-press = "Incline Dumbbell Press"
incline-push-up = "Incline Push Up"
kettlebell-floor-press = "Kettlebell Floor Press"
kneeling-incline-push-up = "Kneeling Incline Push Up"
kneeling-push-up = "Kneeling Push Up"
machine-chest-fly = "Machine Chest Fly"
machine-chest-press = "Machine Chest Press"
pec-deck = "Pec Deck"
pin-bench-press = "Pin Bench Press"
push-up = "Push Up"
push-up-against-wall = "Push Up Against Wall"
push-ups-with-feet-in-rings = "Push Ups With Feet In Rings"
resistance-band-chest-fly = "Resistance Band Chest Fly"
ring-dip = "Ring Dip"
smith-machine-bench-press = "Smith Machine Bench Press"
smith-machine-incline-bench-press = "Smith Machine Incline Bench Press"
smith-machine-reverse-grip-bench-press = "Smith Machine Reverse Grip Bench Press"
standing-cable-chest-fly = "Standing Cable Chest Fly"
standing-resistance-band-chest-fly = "Standing Resistance Band Chest Fly"

[shoulder]
arnold-press = "Arnold Press"
band-external-shoulder-rotation = "Band External Shoulder Rotation"
band-internal-shoulder-rotation = "Band Internal Shoulder Rotation"
band-pull-apart = "Band Pull Apart"
barbell-front-raise = "Barbell Front Raise"
barbell-rear-delt-row = "Barbell Rear Delt Row"
barbell-upright-row = "Barbell Upright Row"
behind-the-neck-press = "Behind The Neck Press"
cable-lateral-raise = "Cable Lateral Raise"
cable-rear-delt-row = "Cable Rear Delt Row"
cuban-press = "Cuban Press"
dumbbell-front-raise = "Dumbbell Front Raise"
dumbbell-horizontal-internal-shoulder-rotation = "Dumbbell Horizontal Internal Shoulder Rotation"
dumbbell-horizontal-external-shoulder-rotation = "Dumbbell Horizontal External Shoulder Rotation"
dumbbell-lateral-raise = "Dumbbell Lateral Raise"
dumbbell-rear-delt-row = "Dumbbell Rear Delt Row"
dumbbell-shoulder-press = "Dumbbell Shoulder Press"
face-pull = "Face Pull"
front-hold = "Front Hold"
landmine-press = "Landmine Press"
lying-dumbbell-external-shoulder-rotation = "Lying Dumbbell External Shoulder Rotation"
lying-dumbbell-internal-shoulder-rotation = "Lying Dumbbell Internal Shoulder Rotation"
machine-lateral-raise = "Machine Lateral Raise"
machine-shoulder-press = "Machine Shoulder Press"
monkey-row = "Monkey Row"
overhead-press = "Overhead Press"
plate-front-raise = "Plate Front Raise"
power-jerk = "Power Jerk"
push-press = "Push Press"
reverse-cable-flyes = "Reverse Cable Flyes"
reverse-dumbbell-flyes = "Reverse Dumbbell Flyes"
reverse-machine-fly = "Reverse Machine Fly"
seated-dumbbell-shoulder-press = "Seated Dumbbell Shoulder Press"
seated-barbell-overhead-press = "Seated Barbell Overhead Press"
seated-smith-machine-shoulder-press = "Seated Smith Machine Shoulder Press"
snatch-grip-behind-the-neck-press = "Snatch Grip Behind The Neck Press"
squat-jerk = "Squat Jerk"
split-jerk = "Split Jerk"

[bicep]
barbell-curl = "Barbell Curl"
barbell-preacher-curl = "Barbell Preacher Curl"
bayesian-curl = "Bayesian Curl"
bodyweight-curl = "Bodyweight Curl"
cable-crossover-bicep-curl = "Cable Crossover Bicep Curl"
cable-curl-with-bar = "Cable Curl With Bar"
cable-curl-with-rope = "Cable Curl With Rope"
concentration-curl = "Concentration Curl"
drag-curl = "Drag Curl"
dumbbell-curl = "Dumbbell Curl"
dumbbell-preacher-curl = "Dumbbell Preacher Curl"
hammer-curl = "Hammer Curl"
incline-dumbbell-curl = "Incline Dumbbell Curl"
machine-bicep-curl = "Machine Bicep Curl"
resistance-band-curl = "Resistance Band Curl"
spider-curl = "Spider Curl"

[tricep]
barbell-standing-triceps-extension = "Barbell Standing Triceps Extension"
barbell-lying-triceps-extension = "Barbell Lying Triceps Extension"
bench-dip = "Bench Dip"
crossbody-cable-triceps-extension = "Crossbody Cable Triceps Extension"
close-grip-push-up = "Close Grip Push Up"
dumbbell-lying-triceps-extension = "Dumbbell Lying Triceps Extension"
dumbbell-standing-triceps-extension = "Dumbbell Standing Triceps Extension"
overhead-cable-triceps-extension = "Overhead Cable Triceps Extension"
tricep-bodyweight-extension = "Tricep Bodyweight Extension"
tricep-pushdown-with-bar = "Tricep Pushdown With Bar"
tricep-pushdown-with-rope = "Tricep Pushdown With Rope"

[legs]
air-squat = "Air Squat"
air-squat = "Air Squat"
barbell-hack-squat = "Barbell Hack Squat"
barbell-lunge = "Barbell Lunge"
barbell-walking-lunge = "Barbell Walking Lunge"
belt-squat = "Belt Squat"
body-weight-lunge = "Body Weight Lunge"
bodyweight-leg-curl = "Bodyweight Leg Curl"
box-jump = "Box Jump"
box-squat = "Box Squat"
bulgarian-split-squat = "Bulgarian Split Squat"
chair-squat = "Chair Squat"
dumbbell-lunge = "Dumbbell Lunge"
dumbbell-squat = "Dumbbell Squat"
front-squat = "Front Squat"
glute-ham-raise = "Glute Ham Raise"
goblet-squat = "Goblet Squat"
hack-squat-machine = "Hack Squat Machine"
half-air-squat = "Half Air Squat"
hip-adduction-machine = "Hip Adduction Machine"
jumping-lunge = "Jumping Lunge"
landmine-hack-squat = "Landmine Hack Squat"
landmine-squat = "Landmine Squat"
leg-curl-on-ball = "Leg Curl On Ball"
leg-extension = "Leg Extension"
leg-press = "Leg Press"
lying-leg-curl = "Lying Leg Curl"
nordic-hamstring-eccentric = "Nordic Hamstring Eccentric"
pause-squat = "Pause Squat"
pistol-squat = "Pistol Squat"
reverse-barbell-lunge = "Reverse Barbell Lunge"
romanian-deadlift = "Romanian Deadlift"
safety-bar-squat = "Safety Bar Squat"
seated-leg-curl = "Seated Leg Curl"
shallow-body-weight-lunge = "Shallow Body Weight Lunge"
side-lunges-bodyweight  = "Side Lunges Bodyweight "
smith-machine-bulgarian-split-squat = "Smith Machine Bulgarian Split Squat"
smith-machine-front-squat = "Smith Machine Front Squat"
smith-machine-squat = "Smith Machine Squat"
squat = "Squat"
step-up = "Step Up"
zercher-squat = "Zercher Squat"
zombie-squat = "Zombie Squat"


[back]
assisted-chin-up = "Assisted Chin Up"
assisted-pull-up = "Assisted Pull Up"
back-extension = "Back Extension"
banded-muscle-up = "Banded Muscle Up"
barbell-row = "Barbell Row"
barbell-shrug = "Barbell Shrug"
block-clean = "Block Clean"
block-snatch = "Block Snatch"
cable-close-grip-seated-row = "Cable Close Grip Seated Row"
cable-wide-grip-seated-row = "Cable Wide Grip Seated Row"
chest-to-bar = "Chest To Bar"
chin-up = "Chin Up"
clean = "Clean"
clean-and-jerk = "Clean And Jerk"
deadlift = "Deadlift"
deficit-deadlift = "Deficit Deadlift"
dumbbell-deadlift = "Dumbbell Deadlift"
dumbbell-row = "Dumbbell Row"
dumbbell-shrug = "Dumbbell Shrug"
floor-back-extension = "Floor Back Extension"
good-morning = "Good Morning"
gorilla-row = "Gorilla Row"
hang-clean = "Hang Clean"
hang-power-clean = "Hang Power Clean"
hang-power-snatch = "Hang Power Snatch"
hang-snatch = "Hang Snatch"
inverted-row = "Inverted Row"
inverted-row-with-underhand-grip = "Inverted Row With Underhand Grip"
jefferson-curl = "Jefferson Curl"
jumping-muscle-up = "Jumping Muscle Up"
kettlebell-swing = "Kettlebell Swing"
lat-pulldown-with-pronated-grip = "Lat Pulldown With Pronated Grip"
lat-pulldown-with-supinated-grip = "Lat Pulldown With Supinated Grip"
muscle-up-bar = "Muscle Up Bar"
muscle-up-rings = "Muscle Up Rings"
one-handed-cable-row = "One Handed Cable Row"
one-handed-lat-pulldown = "One Handed Lat Pulldown"
pause-deadlift = "Pause Deadlift"
pendlay-row = "Pendlay Row"
power-clean = "Power Clean"
power-snatch = "Power Snatch"
pull-up = "Pull Up"
pull-up-with-a-neutral-grip = "Pull Up With A Neutral Grip"
rack-pull = "Rack Pull"
ring-pull-up = "Ring Pull Up"
ring-row = "Ring Row"
scap-pull-up = "Scap Pull Up"
seal-row = "Seal Row"
seated-machine-row = "Seated Machine Row"
single-leg-deadlift-with-kettlebell = "Single Leg Deadlift With Kettlebell"
smith-machine-one-handed-row = "Smith Machine One Handed Row"
snatch = "Snatch"
snatch-grip-deadlift = "Snatch Grip Deadlift"
stiff-legged-deadlift = "Stiff Legged Deadlift"
straight-arm-lat-pulldown = "Straight Arm Lat Pulldown"
sumo-deadlift = "Sumo Deadlift"
t-bar-row = "T Bar Row"
trap-bar-deadlift-with-high-handles = "Trap Bar Deadlift With High Handles"
trap-bar-deadlift-with-low-handles = "Trap Bar Deadlift With Low Handles"

[glute]
banded-side-kicks = "Banded Side Kicks"
cable-pull-through = "Cable Pull Through"
clamshells = "Clamshells"
cossack-squat = "Cossack Squat"
death-march-with-dumbbells = "Death March With Dumbbells"
donkey-kicks = "Donkey Kicks"
dumbbell-romanian-deadlift = "Dumbbell Romanian Deadlift"
dumbbell-frog-pumps = "Dumbbell Frog Pumps"
fire-hydrants = "Fire Hydrants"
frog-pumps = "Frog Pumps"
glute-bridge = "Glute Bridge"
hip-abduction-against-band = "Hip Abduction Against Band"
hip-abduction-machine = "Hip Abduction Machine"
hip-thrust = "Hip Thrust"
hip-thrust-machine = "Hip Thrust Machine"
hip-thrust-with-band-around-knees = "Hip Thrust With Band Around Knees"
lateral-walk-with-band = "Lateral Walk With Band"
machine-glute-kickbacks = "Machine Glute Kickbacks"
one-legged-glute-bridge = "One Legged Glute Bridge"
one-legged-hip-thrust = "One Legged Hip Thrust"
reverse-hyperextension = "Reverse Hyperextension"
romanian-deadlift = "Romanian Deadlift"
single-leg-romanian-deadlift = "Single Leg Romanian Deadlift"
standing-glute-kickback-in-machine = "Standing Glute Kickback In Machine"
step-up = "Step Up"

[abs]
ball-slams = "Ball Slams"
cable-crunch = "Cable Crunch"
crunch = "Crunch"
dead-bug = "Dead Bug"
dragon-flag = "Dragon Flag"
hanging-knee-raise = "Hanging Knee Raise"
hanging-leg-raise = "Hanging Leg Raise"
hanging-sit-up = "Hanging Sit Up"
hanging-windshield-wiper = "Hanging Windshield Wiper"
hollow-body-hold = "Hollow Body Hold"
high-to-low-wood-chop-with-band = "High To Low Wood Chop With Band"
horizontal-wood-chop-with-band = "Horizontal Wood Chop With Band"
jackknife-sit-up = "Jackknife Sit Up"
kneeling-ab-wheel-roll-out = "Kneeling Ab Wheel Roll Out"
kneeling-plank = "Kneeling Plank"
kneeling-side-plank = "Kneeling Side Plank"
l-sit = "L Sit"
lying-leg-raise = "Lying Leg Raise"
lying-windshield-wiper = "Lying Windshield Wiper"
lying-windshield-wiper-with-bent-knees = "Lying Windshield Wiper With Bent Knees"
machine-crunch = "Machine Crunch"
mountain-climbers = "Mountain Climbers"
oblique-crunch = "Oblique Crunch"
oblique-sit-up = "Oblique Sit Up"

[calves]
barbell-standing-calf-raise = "Barbell Standing Calf Raise"
donkey-calf-raise = "Donkey Calf Raise"
eccentric-heel-drop = "Eccentric Heel Drop"
heel-raise = "Heel Raise"
seated-calf-raise = "Seated Calf Raise"
standing-calf-raise = "Standing Calf Raise"

[forearm-flexor-and-grip]
barbell-wrist-curl = "Barbell Wrist Curl"
barbell-wrist-curl-behind-the-back = "Barbell Wrist Curl Behind The Back"
bar-hang = "Bar Hang"
dumbbell-wrist-curl = "Dumbbell Wrist Curl"
farmers-walk = "Farmers Walk"
fat-bar-deadlift = "Fat Bar Deadlift"
gripper = "Gripper"
one-handed-bar-hang = "One Handed Bar Hang"
plate-pinch = "Plate Pinch"
plate-wrist-curl = "Plate Wrist Curl"
towel-pull-up = "Towel Pull Up"
wrist-roller = "Wrist Roller"

[forearm-extensor]
barbell-wrist-extension = "Barbell Wrist Extension"
dumbbell-wrist-extension = "Dumbbell Wrist Extension"

[cardio]
bike = "Bike"
rowing-machine = "Rowing Machine"
running = "Running"
stationary-bike = "Stationary Bike"
